CoffeeShop/Models/ErrorViewModel.cs
using System;

namespace CoffeeShop.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoffeeShop/Models/RegisterUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoffeeShop.Models
{
    public class RegisterUser
    {
        [Required]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Must be between 2 and 30 characters")]
        public string Name { get; set; }
        [Required]
        [StringLength(12, MinimumLength = 8, ErrorMessage = "Must be between 8 and 12 characters")]
        public string Password { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9{5,30}]+@[a-zA-A0-9{5,10}]+\.[a-zA-Z0-9{2,3}]+$")]
        public string Email { get; set; }
        [Required]
        public DateTime DOB { get; set; }
        [Required]
        public bool Human { get; set; }

        
    }
}

CoffeeShop/Controllers/CoffeeShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoffeeShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class CoffeeShopController : Controller
    {
        public IActionResult Registration()
        {
            return View(new RegisterUser());
        }
        public IActionResult Summary(RegisterUser user)
        {
            //return View(user);
            if (ModelState.IsValid)
            {
                return View(user);
            }
            else
            {
                return View("Registration", user);
            }
        }
    }
}

CoffeeShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CoffeeShop.Models;

namespace CoffeeShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoffeeShop/Views/CoffeeShop/Registration.cshtml
@{
    ViewData["Title"] = "Registration";
}

<h1>Registration</h1>
@Html.ValidationSummary()

<form action="../CoffeeShop/Summary" method="post">
    <input type="text" name="Name" placeholder="Name" value="@Model.Name" /><br /><br />
    <input type="password" name="Password" placeholder="Password" value="@Model.Password" /><br /><br />
    <input type="text" name="Email" placeholder="Email" value="@Model.Email" /><br /><br />
    <input type="checkbox" name="Human" value=True /><br /><br />
    <input type="date" name="DOB" /><br /><br />
    <input type="submit" value="Add new user!" />
</form>

CoffeeShop/Views/CoffeeShop/Summary.cshtml
@{
    ViewData["Title"] = "Summary";
}

@model RegisterUser
<h1>Summary</h1>

<p>@Model.Name</p>

CoffeeShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoffeeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoffeeShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CoffeeShop" asp-action="Registration">CoffeShop</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CoffeeShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>